name: CI Workflow

on:
  push:
    branches:
      - main
      - develop

permissions:
  id-token: write 
  contents: read    

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Get OIDC token
        run: |
          value=$(curl -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=api://AzureADTokenExchange" | jq '.value')
          token=$(curl -X POST -H "Content-Type: application/json" -d "{\"oidc_token\":$value, \"service_slug\":\"bot-iWBX\"}" https://api.cloudsmith.io/openid/testcheck-HrHX/ | jq -r '.token')
          curl --request GET --url https://api.cloudsmith.io/v1/user/self/ --header "X-Api-Key:Bearer $token" --header 'accept: application/json'
                    
          echo "CLOUDSMITH_API_KEY=$token" >> $GITHUB_ENV
   
      - name : Push
    # runs-on: ubuntu-latest
    # name: Python Push Demo
    # steps:
    #   - uses: actions/checkout@v4
    #   - name: Push
        id: push
        uses: cloudsmith-io/action@v0.5.3
        with:
         api-key: ${{ env.CLOUDSMITH_API_KEY }}
         command: "push"
         format: "python"
         owner: "testcheck-HrHX"
         repo: "new1"
         file: "mypackage-0.1.tar.gz"
